---
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags: ntp

- name: Install NTP - Debian
  apt: name=ntp state=installed
  when: ansible_os_family == 'Debian'
  tags: ntp

- name: Install NTP - RHEL
  yum: name=ntp state=installed
  when: ansible_os_family == 'RedHat'
  tags: ntp

- name: Configure NTP service
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  tags: ntp
  notify: restart ntp

- name: Ensure NTP is started
  service: name={{ ntp_service_name }} state=started enabled=yes
  tags: ntp
