---
- hosts: all

  tasks:
    - group_by: "key=os_{{ansible_distribution | lower}}"
      changed_when: False

- hosts:
    - os_centos
    - os_redhat
  gather_facts: no

  roles:
    - clock
    - banners
    - ntp
    - ssh-server
    - sudo
    - users
    - profile
    - epel
