---
- hosts: all
  sudo: yes
  vars_files:
    - vars/yumreposd.yml

  roles:
    - clock
    - banners
    - ntp
    - sudo
    - profile
    - { role: users, when: "ansible_os_family == 'RedHat'" }
    - { role: epel, when: "ansible_os_family == 'RedHat'" }
    - { role: yumreposd, when: "ansible_os_family == 'RedHat'" }
    - { role: yum-cron, when: "ansible_os_family == 'RedHat'" }
    - ssh-server