# Ansible playbook to cleanly reboot a host, subject to successful pre/post testing

- hosts: all
  sudo: true

  tasks:
    - name: Ensure BATS is installed
      yum: name=bats state=latest
    
    - name: Perform pre-reboot checks
      command: bats /home/jon/bats/pass.bats
      changed_when: false
      always_run: yes
    
    - name: Reboot the host
      shell: sleep 2 && shutdown -r now 'Ansible-triggered reboot in progress'
      async: 1
      poll: 0
      ignore_errors: true
    
    - name: Wait for host to come back to life
      local_action: wait_for host={{ inventory_hostname }}
                    port=22
                    delay=10
                    state=started
      sudo: false
      always_run: yes
    
    - name: Run post-reboot testing
      command: bats /home/jon/bats/pass.bats
      changed_when: false
