# Ansible playbook to patch and reboot a host

- hosts: all
  gather_facts: false

  tasks:
    - name: Update all packages
      yum: name=* state=latest update_cache=yes
    
    - name: Reboot the host
      shell: sleep 2 && shutdown -r now 'Ansible-triggered reboot in progress'
      async: 1
      poll: 0
      ignore_errors: true
    
    - name: Wait for host to come back to life
      local_action: wait_for host={{ inventory_hostname }}
                    port=22
                    delay=10
                    state=started
      become: no
      always_run: yes
