---
# Common system configuration

- name: Install NTP
  yum: name=ntp state=installed
  tags: ntp

- name: Configure NTP service
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  tags: ntp
  notify: restart ntp

- name: Ensure NTP is started
  service: name=ntpd state=started enabled=yes
  tags: ntp


- name: Configure MOTD
  template: src=motd.j2 dest=/etc/motd
  tags: banner

- name: Configure /etc/issue
  copy: src=issue dest=/etc/issue
  tags: banner

- name: Configure /etc/issue.net
  file: src=/etc/issue dest=/etc/issue.net state=link force=true
  tags: banner


- name: Configure system timezone
  file: src=/usr/share/zoneinfo/{{ timezone }} dest=/etc/localtime state=link force=yes

- name: Install SSH server
  yum: name=openssh state=installed
  tags: sshd

- name: Configure SSH server
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config
  tags: sshd
  notify: restart sshd

- name: Ensure SSH server is running
  service: name=sshd state=started enabled=yes
  tags: sshd


- name: Configure /etc/sudoers
  copy: src=sudoers dest=/etc/sudoers
  tags: sudo

- name: Ensure /etc/sudoers.d exists
  file: dest=/etc/sudoers.d state=directory owner=root group=root mode=0550
  tags: sudo


- name: Configure default system prompt
  copy: src=prompt.sh dest=/etc/profile.d/prompt.sh mode=0755
  tags: profile

- name: Add 'jon' group
  group: name=jon gid=4556

- name: Add 'jon' User
  user: name=jon comment='Jon Fautley' uid=4556 group=jon createhome=yes groups=wheel password='*LK*'

- name: Add SSH key for jon
  authorized_key: user=jon key="{{ lookup('file', '/Users/jon/.ssh/id_dsa.pub') }}"
